# Generated by Django 2.1.4 on 2020-12-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contest_Test_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=32, verbose_name='试卷名')),
                ('years', models.CharField(max_length=4, verbose_name='真题年份')),
                ('course', models.CharField(max_length=16, verbose_name='真题科目')),
                ('level', models.CharField(max_length=16, verbose_name='真题级别')),
                ('c_type', models.BooleanField(default=True, verbose_name='是否数学专业')),
                ('contest_address', models.CharField(max_length=16, verbose_name='竞赛地区')),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('addrs', models.URLField(blank=True, null=True, verbose_name='试卷资料地址')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '竞赛真题试卷表',
                'verbose_name_plural': '竞赛真题试卷表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=16, verbose_name='课程名称')),
                ('course_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='课程图片')),
                ('course_credit', models.FloatField(verbose_name='学分')),
                ('start_time', models.DateField(auto_now=True, verbose_name='开课时间')),
                ('end_time', models.DateField(auto_now=True, verbose_name='结课时间')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '课程信息表',
                'verbose_name_plural': '课程信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course_detial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_detail_name', models.CharField(max_length=16, verbose_name='章节名称')),
                ('chapter', models.CharField(max_length=8, verbose_name='章')),
                ('sector', models.CharField(max_length=8, verbose_name='节')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('1', 'pdf'), ('2', 'word')], default='1', max_length=4, verbose_name='资料类型')),
                ('data_name', models.CharField(max_length=16, verbose_name='资料名称')),
                ('content', models.TextField(max_length=200, verbose_name='资料信息')),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('addrs', models.URLField(blank=True, null=True, verbose_name='资料地址')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
            options={
                'verbose_name': '课程资料',
                'verbose_name_plural': '课程资料',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('grade', models.FloatField(verbose_name='分数')),
                ('addrs', models.URLField(blank=True, null=True, verbose_name='作业地址')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=32, verbose_name='公告标题')),
                ('content', models.TextField(max_length=500, verbose_name='公告内容')),
                ('post_time', models.TimeField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pro_Test_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=32, verbose_name='试卷名')),
                ('years', models.CharField(max_length=4, verbose_name='真题年份')),
                ('course', models.CharField(max_length=16, verbose_name='真题科目')),
                ('university', models.CharField(max_length=16, verbose_name='真题学校')),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('addrs', models.URLField(blank=True, null=True, verbose_name='试卷资料地址')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '专业课真题试卷表',
                'verbose_name_plural': '专业课真题试卷表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Public_Test_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=32, verbose_name='试卷名')),
                ('years', models.CharField(max_length=4, verbose_name='真题年份')),
                ('math_type', models.CharField(choices=[('1', '数学一'), ('2', '数学二'), ('3', '数学三')], default='1', max_length=16, verbose_name='试卷类型')),
                ('upload_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('addrs', models.URLField(blank=True, null=True, verbose_name='试卷资料地址')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '公共课真题试卷表',
                'verbose_name_plural': '公共课真题试卷表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stu_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0, verbose_name='分数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
            options={
                'verbose_name': '总成绩',
                'verbose_name_plural': '总成绩',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='male', max_length=16, null=True, verbose_name='性别')),
                ('student_id', models.CharField(max_length=16, verbose_name='学号')),
                ('university', models.CharField(max_length=16, verbose_name='学校')),
                ('college', models.CharField(max_length=16, verbose_name='学院')),
                ('profession', models.CharField(max_length=32, verbose_name='专业')),
                ('student_class', models.CharField(max_length=16, verbose_name='班级')),
                ('register_date', models.DateField(auto_now=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '学生信息表',
                'verbose_name_plural': '学生信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='male', max_length=16, null=True, verbose_name='性别')),
                ('university', models.CharField(max_length=16, verbose_name='学校')),
                ('college', models.CharField(max_length=16, verbose_name='学院')),
                ('profession', models.CharField(max_length=32, verbose_name='专业')),
                ('register_date', models.DateField(auto_now=True, verbose_name='注册时间')),
                ('teacher_id', models.CharField(max_length=16, verbose_name='工号')),
            ],
            options={
                'verbose_name': '教师信息表',
                'verbose_name_plural': '教师信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Test_paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=32, verbose_name='试卷名')),
                ('upload_time', models.DateField(auto_now=True, verbose_name='上传时间')),
                ('addrs', models.URLField(blank=True, null=True, verbose_name='试卷资料地址')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
            options={
                'verbose_name': '试卷信息表',
                'verbose_name_plural': '试卷信息表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('telephone', models.CharField(max_length=16, verbose_name='电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在任')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=16, verbose_name='视频名称')),
                ('addrs', models.URLField(blank=True, null=True, verbose_name='视频地址')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
            options={
                'verbose_name': '视频表',
                'verbose_name_plural': '视频表',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='test_paper',
            name='upload_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserInfo'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserInfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserInfo'),
        ),
        migrations.AddField(
            model_name='stu_grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.StudentInfo'),
        ),
        migrations.AddField(
            model_name='stu_grade',
            name='test_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Test_paper'),
        ),
        migrations.AddField(
            model_name='notice',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserInfo'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.StudentInfo'),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='upload_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserInfo'),
        ),
        migrations.AddField(
            model_name='course_detial',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Video'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TeacherInfo'),
        ),
    ]
