# Generated by Django 2.1.4 on 2020-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stu_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='课程图片'),
        ),
    ]
