# Generated by Django 2.1.4 on 2020-12-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201212_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='course_img', verbose_name='课程图片'),
        ),
    ]
